Add tool to anonymize HAR files
pento/free-as-in-speech pull request #30
Opened 2021-03-04 16:37 UTC by akirk

As mentioned in our [Working with the Command-line](https://github.com/pento/free-as-in-speech/blob/anonymize-har/docs/contributors/command-line.md) docs, HAR files can contain PII (Personally Identifiable Information) which we want to avoid.

Thus, this implements a tool that can rewrite HAR files to be more anonymous. Since it contains a list of rules, there might still be some rules missing so that it needs to be reviewed from time to time.

## Testing instructions

Run the script on a HAR file:
```
$ node packages/fetch-from-har/bin/anonymize-har.js test.har
Reading test.har...

The following number of items were replaced:
 - 762 timestamp
 - 13 ipv4
 - 5 ipv6
 - 78 email
 - 948 uuid
 - 1 wixSite
 - 1 _wixUIDX
 - 1 mediaToken
 - 1 wixSession2
 - 10 authorization
 - 3 session_id
 - 176 request_id
Wrote anonymized-test.har.
```

Then verify that the anonymized file contains changes and that it still works fine:
```
$ diff test.har anonymized-test.har | wc -l
   21608
$ diff test.har anonymized-test.har | $EDITOR
$ open anonymized-test.har|
```

Fixes #24

2021-03-08 07:17 UTC, yoavf reviewed
Tested, works well - both on anonymizing the file, and making sure the file still works with `export-from-har.js` 

Added a few suggestions for additional data to anonymize.

2021-03-08 07:17 UTC, yoavf commented on packages/fetch-from-har/bin/anonymize-har.js
> +	},
Should we also anonymize the user-agent?
```
 {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
            },
```

2021-03-08 07:17 UTC, yoavf commented on packages/fetch-from-har/bin/anonymize-har.js
> +};
There are a few other cookies (and matching headers) that we might want to anonymize or even completely remove (assuming extracting still works):

- `svSession` - "Used in connection with user login", and `XSRF-TOKEN` -"Used for security reasons" . `TS*`  - "Used for security and anti-fraud reasons" [Reference here](https://support.wix.com/en/article/cookies-and-your-wix-site) 
- `_wixAB3` - probably some ab testing
- `_ga` - Google Analytics
- `_gcl_au` - Google Tag Manager

For the headers, can we anonymize/remove:
- x-seen-by (wix specific)

2021-03-10 03:35 UTC, pento requested changes
We'll probably want to reuse this code when we allow users to submit debug info, but it looks relatively straightforward to convert the code to something importable.

One minor thing to change, there shouldn't be a `package-lock.json` in the package folder: this can be fixed by removing that file, and running `npm i` in the base folder.

2021-03-11 15:11 UTC, akirk commented
@pento done and rebased.

2021-03-12 06:06 UTC, pento approved these changes
🚢

2021-03-12 10:05 UTC, merged